services:
  httpbin:
    image: ghcr.io/zerocluster/httpbin
    # depends_on: [postgresql]
    init: true
    stop_grace_period: 5m

    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1

    command: run

    # secrets:
    #   - { source: httpbin_env.yaml, target: /var/local/package/env.yaml }

    networks: [network]

    volumes:
      - { type: tmpfs, target: /dev/shm, tmpfs: { size: 1073741824 } }

    build: .

# secrets:
#   httpbin_env.yaml: { file: env.production.local.yaml }

networks:
  network: ~
